on:
  release:
    types:
      - published

name: release

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Used to sign the artifacts.
      contents: write # Used to attach signing artifacts to the release.

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: sign
        uses: ./
        id: sigstore-python
        with:
          inputs: action.yml action.py
